version: '3.8'

services:

  db:
    image: mysql:latest
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - db:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'fizyka'
      MYSQL_PASSWORD: 'password'
    networks:
      - app_network
    command: --init-file=/docker-entrypoint-initdb.d/fizyka.sql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db:
